# Generated by Django 3.2.5 on 2022-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='isDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adviser',
            name='isLoggedIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='available_anytime',
            field=models.IntegerField(default=0),
        ),
    ]
