# Generated by Django 3.2.5 on 2022-04-11 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_code',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 11, 14, 30, 5, 85883)),
        ),
    ]
