# Generated by Django 3.2.5 on 2022-03-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20220223_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(max_length=100)),
                ('meeting_urgency', models.CharField(max_length=100)),
                ('meeting_status', models.IntegerField(default=0)),
                ('meeting_counselor', models.CharField(max_length=100)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='sample.student')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
