# Generated by Django 3.2.7 on 2022-03-18 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_appointment_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 13, 18, 57, 376509)),
        ),
    ]
