# Generated by Django 4.0.1 on 2022-03-30 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20220330_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 0, 56, 13, 304350)),
        ),
    ]
