# Generated by Django 3.2.5 on 2022-04-12 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_alter_appointment_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 12, 18, 6, 17, 923165)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
