# Generated by Django 3.2.5 on 2022-04-12 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20220412_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 13, 0, 50, 2, 923903)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
