# Generated by Django 4.0.1 on 2022-04-12 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20220413_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 13, 1, 34, 23, 438172)),
        ),
    ]
